# Generated by Django 4.1 on 2022-08-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='datecompleted',
        ),
        migrations.AddField(
            model_name='todo',
            name='bool',
            field=models.BooleanField(default=False),
        ),
    ]
